### PR TITLE
Add Installer

### PR DESCRIPTION
**Pull request by RedstoneWizard08**
Checklist (pls dont merge yet):
- [x] Make executable
- [x] Download file
- [ ] Extract file (sometimes it fails)
- [x] Clean up
- [ ] Handle exceptions
- [ ] Add logger

### CODE REVIEW

**Comment by SeanErn** [comment]
maybe convert this to a draft pr if you don't want it merged yet

**Comment by RedstoneWizard08** [comment]
i dont know how :p

**Comment by SeanErn** [comment]
> i dont know how :p

by the section that says reviewers there's a button that says convert to draft pr. Or there should be

**Comment by Rexicon226** [comment]
:< i already made a installer :<

**Pull request closed without merging**
