### PR TITLE
Optimized load order resolver method

### PR DESCRIPTION
**Pull request by EwyBoy**
In this optimized version of the code, I create a new HashSet called resolvedDependencies to track which mod dependencies have already been resolved. I then check whether the HashSet contains the current mod's name or whether its dependencies are already resolved, and only add it to _modLoadOrder if it hasn't already been added. I also add the mod's name to the resolvedDependencies HashSet to track that its dependencies have been resolved.

By using a HashSet to track resolved dependencies, we can avoid iterating through the entire list of enabled mods for each pass of the loop, which can potentially reduce the number of iterations needed to resolve all dependencies.

### CODE REVIEW

**Comment by EwyBoy** [comment]
Potential breaking change, I have not testet it yet properly.

**Comment by EwyBoy** [comment]
Are you able to test it?

**Comment by cheese3660** [comment]
I don't think any mods use dependency system right now so I'd quickly have to make one

**Comment by cheese3660** [comment]
Pushing back to post-0.3.0

**Pull request closed without merging**
