### PR TITLE
Completely switch to BepInEx

### PR DESCRIPTION
**Pull request by Windows10CE**
Refs #105

### CODE REVIEW

**Comment by cheese3660** [comment]
Accidentally marked as ready

**Comment by Rexicon226** [comment]
whoops

**Comment by EwyBoy** [comment]
This is starting to look really good

**Review by cheese3660 — APPROVED** [review]
Looks good to me, one thing I will change in the main version after discussion with @X606 is to have a [SpaceWarpLoad] attribute that makes it exceedingly obvious that the user wants space warp to load this.

**Comment by cheese3660** [comment]
Still a draft though I suppose

**Comment by Halbann** [comment]
Please could you add LoadIcon() back in.

**Comment by cheese3660** [comment]
(What this does is loads a 24x24 icon next to the assembly iirc)

**Comment by cheese3660** [comment]
I mean the other option for some reason, would be to have the Icon be a field in the plugin, that gets autopopulated, but that sounds kinda jank

**Comment by adamsong** [comment]
> Please could you add LoadIcon() back in.

Make an asset bundle, its not hard, and that is auto loaded. If you *need* to load an icon at runtime, see example mod.

**Comment by cheese3660** [comment]
@Halbann 
LoadIcon() still exists, example in ExampleMod.cs
`LoadIcon(Path.Combine(PluginFolderPath, "icon.png"))`

**Comment by cheese3660** [comment]
Oh wait thats in example mod only, my bad

**Comment by adamsong** [comment]
> Looks good to me, one thing I will change in the main version after discussion with @X606 is to have a [SpaceWarpLoad] attribute that makes it exceedingly obvious that the user wants space warp to load this.

If you want to add an optional attribute that does nothing to make people feel better, you can, but [BepInPlugin] would still be required, and the mod class would inherit from `BaseSpaceWarpPlugin` so all [SpaceWarpLoad] would do is be a comment.

**Comment by cheese3660** [comment]
one other problem in example mod, do we not expose the skin of Space Warp with space warp, as the way its loading the skin won't work with the changes we made
"space_warp/swconsoleui/swconsoleUI/spacewarpConsole.guiskin"
should be
"space_warp/swconsoleui/spaceWarpConsole.guiskin"
now

**Comment by cheese3660** [comment]
> one other problem in example mod, do we not expose the skin of Space Warp with space warp, as the way its loading the skin won't work with the changes we made "space_warp/swconsoleui/swconsoleUI/spacewarpConsole.guiskin" should be "space_warp/swconsoleui/spaceWarpConsole.guiskin" now

Speaking of this
```cs
if (assetName.StartsWith("assets/"))
	assetName = assetName["assets/".Length..];
if (assetName.StartsWith(assetBundleName + "/"))
	assetName = assetName[(assetBundleName.Length + 1)..];
```
In AssetManager.cs
should be
```cs
if (assetName.ToLower().StartsWith("assets/"))
	assetName = assetName["assets/".Length..];
if (assetName.ToLower().StartsWith(assetBundleName + "/"))
	assetName = assetName[(assetBundleName.Length + 1)..];
```
As unityfs is case insensitive, and people for some reason are passing cased names

**Comment by adamsong** [comment]
> Loading an icon is something that every mod author wants to do

Feels like bloat to add a function whose only use is generating tech debt.

**Comment by cheese3660** [comment]
This is where we instead add an `assets/images` path where the images are loaded into the asset manager?

**Comment by cheese3660** [comment]
It's more in line with the other ways we do things

**Comment by adamsong** [comment]
No, that is worse, if we do pull it back, it should be marked to throw a warning when used. I do not want some mod pulling in a bunch of pngs just because its easier than making a bundle.

**Comment by Halbann** [comment]
> No, that is worse, if we do pull it back, it should be marked to throw a warning when used. I do not want some mod pulling in a bunch of pngs just because its easier than making a bundle.

Why not? It seems like you’re being obtuse for no practical reason. Please explain.

**Comment by cheese3660** [comment]
In terms of making a bundle we can provide a quick tutorial on making bundles for space warp to load
image
The script for doing it in unity is about that large

**Comment by adamsong** [comment]
https://www.youtube.com/watch?v=C9iCepn0E5c

**Comment by cheese3660** [comment]
> I understand the reluctance of needing to download and install Unity and learn how to use it just in order to get in a single icon for an otherwise code-only mod.

I do too, it requires a large external tool that is frankly a pain to use at times.

**Comment by Halbann** [comment]
> I understand the reluctance of needing to download and install Unity and learn how to use it just in order to get in a single icon for an otherwise code-only mod.

Thank you, this is my point exactly. The process involved is entirely disportional to the goal, in this specific case of loading an icon for the app bar, and especially for new code-only modders.

**Comment by NipperySlipples** [comment]
I guarantee you if we do not add the method back every single one of the
kerbal developers will just add it into there mods or another dependency
mod will end up existing. Like a littoral "spacewalk icon loader". I said
when you removed it this would happen lol. Ease of use is critical here and
none of them will download unity. They want to write code with an app or
better yet have there changes loaded through a text file Jason format. Not
edit stuff in unity.

**Comment by cheese3660** [comment]
@Windows10CE is there anything more you need to do before we can fully review this?

**Review by EwyBoy — APPROVED** [review]

**Pull request merged**
