### PR TITLE
Toolbar integration

### PR DESCRIPTION
**Pull request by cheese3660**
This contains code for creating mod toolbar hooks.
This also updates a lot of the UI assets for more general mod use.

### CODE REVIEW

**Review by Rexicon226 — APPROVED** [review]
👍

**Review by Rexicon226 — APPROVED** [review]
👍

**Comment by Halbann** [comment]
The toolbar strings are not hooked up to the function parameters

**Comment by cheese3660** [comment]
How not?

**Comment by cheese3660** [comment]
I'll make another pr

**Pull request merged**
